#!/usr/bin/env bash
set -euo pipefail

: "${SKILL_MANAGER_BIN_DIR:?SKILL_MANAGER_BIN_DIR is required}"
: "${SKILL_MANAGER_CACHE_DIR:?SKILL_MANAGER_CACHE_DIR is required}"
: "${SKILL_DIR:?SKILL_DIR is required}"
: "${SKILL_NAME:=skt}"

# skt is stdlib-only but needs python >= 3.11 (tomllib). macOS's
# /usr/bin/python3 is 3.9, so a bare `python3` in the wrapper breaks the
# moment PATH is minimal. Probe at INSTALL time and bake the absolute
# interpreter into the wrapper; SKT_PYTHON overrides for tests/pins.
#
# The interpreter is the ONE absolute path this wrapper may carry, because it
# is a fact about the MACHINE and not about a home: it lives outside every
# Skill Manager home, so copying the wrapper into another home does not make
# it reach back into this one. Everything the wrapper runs that DOES live in a
# home is resolved below, from the home the wrapper is standing in.
pick_python() {
  if [[ -n "${SKT_PYTHON:-}" ]]; then
    printf '%s' "$SKT_PYTHON"; return 0
  fi
  for candidate in python3.14 python3.13 python3.12 python3.11 python3 python; do
    local resolved
    resolved="$(command -v "$candidate" 2>/dev/null)" || continue
    if "$resolved" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' 2>/dev/null; then
      printf '%s' "$resolved"; return 0
    fi
  done
  return 1
}

PY="$(pick_python)" || {
  echo "skt install requires python >= 3.11 (tomllib); none found on PATH" >&2
  exit 127
}

ENTRYPOINT="$SKILL_DIR/src/skt/cli.py"
if [[ ! -f "$ENTRYPOINT" ]]; then
  echo "skt entrypoint not found at $ENTRYPOINT" >&2
  exit 1
fi

# The entrypoint's location RELATIVE TO A HOME, which is the thing the wrapper
# is allowed to remember. `$SKILL_DIR` is this home's spelling of it and would
# be a different home's spelling the moment the wrapper is copied — that is
# the whole of skill-manager#262, and baking it is what this installer used to
# do. HOME is derived rather than required so the wrapper contract does not
# depend on one more env var than the shim itself needs: bin/cli is always
# `<home>/bin/cli`.
HOME_DIR="$(cd -- "${SKILL_MANAGER_HOME:-$SKILL_MANAGER_BIN_DIR/../..}" && pwd -P)"
ENTRYPOINT_REAL="$(cd -- "$(dirname -- "$ENTRYPOINT")" && pwd -P)/$(basename -- "$ENTRYPOINT")"
case "$ENTRYPOINT_REAL" in
  "$HOME_DIR"/*) REL="${ENTRYPOINT_REAL#"$HOME_DIR"/}" ;;
  *)
    echo "skt install: \$SKILL_DIR ($SKILL_DIR) is not inside the home at $HOME_DIR," >&2
    echo "  so the wrapper has no home-relative path to resolve skt from." >&2
    exit 1
    ;;
esac

mkdir -p "$SKILL_MANAGER_BIN_DIR" "$SKILL_MANAGER_CACHE_DIR"

WRAPPER="$SKILL_MANAGER_BIN_DIR/skt"

# Two heredocs on purpose. The first carries the two INSTALL-TIME facts and is
# expanded; the second is the resolution rule and is quoted, so nothing in it
# can be frozen by accident. A single expanded heredoc is how `$SKILL_DIR`
# ended up in the body in the first place.
cat > "$WRAPPER" <<SH
#!/usr/bin/env bash
# Generated by skill-publisher-skill/skill-scripts/install-skt.sh — do not edit.
#
# Resolves skt from THE HOME THIS WRAPPER LIVES IN: prefer this home's copy,
# fall back to the home this wrapper was pinned to. There is deliberately no
# absolute home path below — a frozen one would send a home that HAS its own
# copy of skt off to run somebody else's.
set -euo pipefail

py="$PY"
rel="$REL"
pinned_home="$SKILL_MANAGER_HOME"
SH

cat >> "$WRAPPER" <<'SH'

# BUILTINS ONLY BELOW THIS LINE, and that is a hard requirement rather than a
# style: this wrapper must answer with NO PATH AT ALL. It is the same reason
# the interpreter above is absolute -- `install-skt.sh` has always said "a bare
# `python3` in the wrapper breaks the moment PATH is minimal" -- and the first
# version of this home-relative resolution reintroduced exactly that bug one
# level over, by calling `dirname` and `readlink`. With PATH empty `dirname`
# is not found, $shim_dir comes back empty, and the wrapper resolves the WRONG
# HOME and then reports that the home holds no copy. sktSurface's
# "wrapper answers with no python on PATH" node caught it.
#
# ${var%/*} and `cd`/`pwd`/`[` are builtins. `dirname` and `readlink` are not.

# The home this wrapper LIVES IN, not the home that installed it. `pwd -P`
# resolves the DIRECTORY's own symlinks and never the wrapper's, so a child
# home whose bin/cli/skt is a link into its parent still answers with itself
# here -- which is the case the preference exists for.
shim="${BASH_SOURCE[0]}"
shim_dir="${shim%/*}"
[ "$shim_dir" = "$shim" ] && shim_dir="."
shim_dir="$(cd -- "$shim_dir" && pwd -P)"
home="$(cd -- "$shim_dir/../.." && pwd -P)"

entrypoint="$home/$rel"

if [ ! -f "$entrypoint" ] && [ -n "$pinned_home" ] && [ -f "$pinned_home/$rel" ]; then
  # THE SANCTIONED FALLBACK, and the only one: this home holds no copy of skt,
  # so run the one this wrapper was pinned to at install time.
  #
  # STORED, NOT FOLLOWED -- and the ordering is what makes that safe. The
  # earlier version followed the wrapper's own symlink chain to avoid a stored
  # path being "taken by a home that has its own copy", but that hazard is
  # about PRECEDENCE, not storage: the home-relative path above is tried
  # FIRST, so a home with its own copy never reaches this line. Following the
  # chain needed `readlink`, which is exactly what the PATH requirement above
  # forbids.
  entrypoint="$pinned_home/$rel"
fi

if [ ! -f "$entrypoint" ]; then
  echo "skt: the home at $home holds no copy of skt ($rel)," >&2
  echo "  and the home this wrapper was pinned to does not either." >&2
  echo "  Install skt into this home, or run the home that owns it." >&2
  exit 127
fi

exec "$py" "$entrypoint" "$@"
SH
chmod 0755 "$WRAPPER"

"$WRAPPER" --help >/dev/null
"$WRAPPER" status --json >/dev/null 2>&1 || {
  echo "skt wrapper failed its status probe (interpreter: $PY)" >&2
  exit 1
}
echo "installed skt for $SKILL_NAME at $WRAPPER (python: $PY, entrypoint: $REL)"
